version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node api service
  api:
    image: nodeapp
    ports:
      - 3030:3030
    depends_on:
      mongo_db:
        condition: service_healthy

volumes:
  mongo_data: {}
