# Generated by Django 5.2.1 on 2025-05-29 21:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarMake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "founded_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1800),
                            django.core.validators.MaxValueValidator(2025),
                        ],
                    ),
                ),
                ("website", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sedan", "Sedan"),
                            ("suv", "SUV"),
                            ("wagon", "Wagon"),
                            ("truck", "Truck"),
                            ("van", "Van"),
                            ("sports", "Sports"),
                            ("luxury", "Luxury"),
                            ("hybrid", "Hybrid"),
                            ("electric", "Electric"),
                        ],
                        default="sedan",
                        max_length=20,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2015),
                            django.core.validators.MaxValueValidator(2023),
                        ]
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50)),
                ("engine", models.CharField(blank=True, max_length=100)),
                ("transmission", models.CharField(blank=True, max_length=50)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "car_make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="djangoapp.carmake",
                    ),
                ),
            ],
        ),
    ]
