# Generated by Django 5.2.1 on 2025-05-29 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dealer",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("zip", models.CharField(max_length=10)),
                ("state", models.CharField(max_length=2)),
                ("lat", models.FloatField()),
                ("long", models.FloatField()),
                ("short_name", models.CharField(max_length=50)),
                ("full_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="type",
            field=models.CharField(
                choices=[
                    ("SEDAN", "Sedan"),
                    ("SUV", "SUV"),
                    ("WAGON", "Wagon"),
                    ("TRUCK", "Truck"),
                    ("VAN", "Van"),
                    ("SPORTS", "Sports"),
                    ("LUXURY", "Luxury"),
                    ("HYBRID", "Hybrid"),
                    ("ELECTRIC", "Electric"),
                ],
                default="SUV",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="year",
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name="carmodel",
            name="dealer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="djangoapp.dealer",
            ),
        ),
    ]
