# Generated by Django 5.2.1 on 2025-05-29 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0002_dealer_alter_carmodel_type_alter_carmodel_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmodel",
            name="year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(2015),
                    django.core.validators.MaxValueValidator(2023),
                ]
            ),
        ),
    ]
